### PR TITLE
copy theme in portal folder fixed

### LINKED ISSUE #110: Apply the theme
Create premium theme folder in /portals/{portalid}/ and compile before applying the theme.

### PR DESCRIPTION
**Pull request by narensingh008**
theme folder copy in portals/{portalid} before applying the theme

### CODE REVIEW

File: DesktopModules/Vanjaro/UXManager/Extensions/Menu/Theme/Controllers/SettingController.cs [hunk 1]
```diff
@@ -68,7 +69,17 @@ private static List<Entities.Theme> GetAllThemes(PortalSettings PortalSettings)
...
+            {
+                string BaseEditorFolder = HttpContext.Current.Server.MapPath("~/Portals/_default/vThemes/" + Theme + "/editor");
+                Core.Managers.SettingManager.Copy(BaseEditorFolder, BaseEditorFolder.Replace("_default", PortalSettings.PortalId.ToString()));
+                try
+                {
+                    ThemeManager.ProcessScss(PortalSettings.PortalId);
+                }
+                catch (System.Exception ex) { DotNetNuke.Services.Exceptions.Exceptions.LogException(ex); }
+                Core.Managers.SettingManager.UpdateValue(PortalSettings.PortalId, -1, "setting_theme", "Theme", Theme);
+            }
```
Comment (mksmanish79) [inline DesktopModules/Vanjaro/UXManager/Extensions/Menu/Theme/Controllers/SettingController.cs:86]: Do this only if the selected theme Theme.css not exists.

**Review by mksmanish79 — APPROVED** [review]

**Review by meetmandeep — APPROVED** [review]
