### PR TITLE
Fixed migration issue

### LINKED ISSUE #333: Error occurred while migrating page.
image

### PR DESCRIPTION
**Pull request by narensingh008**
Closes #333 fixed given key was not present in the dictionary error

### CODE REVIEW

File: DesktopModules/Vanjaro/UXManager/Extensions/Migrate/Components/HttpModule.cs [hunk 1]
```diff
@@ -59,12 +59,14 @@ private void context_PreRequestHandlerExecute(object sender, EventArgs e)
                                 string ControlPanel = HostController.Instance.GetSettings().ContainsKey("ControlPanel") ? HostController.Instance.GetSettings()["ControlPanel"].Value.ToLower() : null;
 
                                 HostController.Instance.GetSettings()["ControlPanel"].Value = "DesktopModules/Vanjaro/UXManager/Library/Base.ascx";
-                                HostController.Instance.GetSettings()["DisableEditBar"].Value = "True";
+                                if (HostController.Instance.GetBoolean("DisableEditBar"))
```
Comment (meetmandeep) [inline DesktopModules/Vanjaro/UXManager/Extensions/Migrate/Components/HttpModule.cs]: @mksmanish79 This doesn't make sense. Can you please review with @narensingh008 

If the value is already true, why set it to true again?

**Review by meetmandeep — CHANGES_REQUESTED** [review]

File: DesktopModules/Vanjaro/UXManager/Extensions/Migrate/Components/HttpModule.cs (hunk 1 above)
Comment (mksmanish79) [reply DesktopModules/Vanjaro/UXManager/Extensions/Migrate/Components/HttpModule.cs]: naren will update this

**Review by mksmanish79 — APPROVED** [review]

File: DesktopModules/Vanjaro/UXManager/Extensions/Migrate/Components/HttpModule.cs (hunk 1 above)
Comment (meetmandeep) [reply DesktopModules/Vanjaro/UXManager/Extensions/Migrate/Components/HttpModule.cs]: @mksmanish79 I still don't get this code. Why set it to true if it's already true?

**Review by meetmandeep — CHANGES_REQUESTED** [review]

**Review by meetmandeep — APPROVED** [review]
