### PR TITLE
#318 improvement program3

### LINKED ISSUE #318: Improvement Program
Collect platform usage data and exceptions to improve and plan future features.

### PR DESCRIPTION
**Pull request by hshimanshusharma**
Close #318

### CODE REVIEW

**Review by meetmandeep — CHANGES_REQUESTED** [review]
Let's review together.

File: DesktopModules/Vanjaro/Core/Library/Managers/AnalyticsManager.cs [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+using System.Web;
+using Vanjaro.Core.Services;
+
+namespace Vanjaro.Core
+{
+    public static partial class Managers
+    {
+        public class AnalyticsManager
+        {
+            internal static void Update(string Version)
```
Comment (meetmandeep) [inline DesktopModules/Vanjaro/Core/Library/Managers/AnalyticsManager.cs]: Remove

File: DesktopModules/Vanjaro/Core/Library/Managers/AnalyticsManager.cs [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+                    Analytics.Event e = new Analytics.Event()
+                    {
+                        name = "exception",
+                        parameter = parameter
+                    };
+                    Analytics.TrackEvent(e);
+                }
+            }
+
+            public static void Post()
```
Comment (meetmandeep) [inline DesktopModules/Vanjaro/Core/Library/Managers/AnalyticsManager.cs:44]: Make internal

File: DesktopModules/Vanjaro/Core/Library/Managers/AnalyticsManager.cs [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+                if (Version == "01.00.00" && !SettingManager.IsVanjaroInstalled())
+                    SettingManager.UpdateHostSetting("AnalyticsUpdate", "install", false);
+                else
+                {
+                    if (SettingManager.GetHostSetting("AnalyticsUpdate", false, string.Empty) == "install")
+                        return;
+                    SettingManager.UpdateHostSetting("AnalyticsUpdate", "upgrade", false);
+                }
+            }
+            public static void TrackException(Exception ex)
```
Comment (meetmandeep) [inline DesktopModules/Vanjaro/Core/Library/Managers/AnalyticsManager.cs]: Need TrackEvent()

File: Portals/_default/Skins/Vanjaro/Base.ascx.cs [hunk 4]
```diff
@@ -213,6 +216,24 @@ private void HandleUXM()
             }
         }
 
+        private void InjectAnalyticsScript()
+        {
+            if (HostController.Instance.GetBoolean("VJImprovementProgram", true))
+            {
```
Comment (meetmandeep) [inline Portals/_default/Skins/Vanjaro/Base.ascx.cs:221]: Post Here

**Review by meetmandeep — APPROVED** [review]
