### PR TITLE
fixed servicesframework undefined issue

### LINKED ISSUE #678: Links token replacement while exporting layouts
Links token replacement while exporting sites,pages,blocks

### LINKED ISSUE #679: servicesframework undefined issue on sign in page

### PR DESCRIPTION
**Pull request by mksmanish79**
closes #679
closes #678

### CODE REVIEW

File: DesktopModules/Vanjaro/UXManager/Extensions/Block/Login/Resources/Scripts/Login.js [hunk 1]
```diff
@@ -264,6 +264,6 @@ $(document).ready(function () {
         }
     });
 
-    Login.UserLoginAPIUri = window.location.origin + $.ServicesFramework(-1).getServiceRoot("Login") + "Login/UserLogin" + window.location.search;
-    
+    setTimeout(function () { Login.UserLoginAPIUri = window.location.origin + $.ServicesFramework(-1).getServiceRoot("Login") + "Login/UserLogin" + window.location.search; });
```
Comment (meetmandeep) [inline DesktopModules/Vanjaro/UXManager/Extensions/Block/Login/Resources/Scripts/Login.js:267]: setTimeout is not allowed unless absolutely needed. Let's review with @Gaganbird

**Review by meetmandeep — APPROVED** [review]
